#!/bin/bash

usage() {
    echo "Usage:"
    echo "  $0              print current cluster usage overview"
    echo "  $0 <user>       print current cluster usage overview for specific <user>"
    echo "  $0 -h/--help    print this message"    
}

[[ "$1" == "-h" ]] && usage && exit
[[ "$1" == "--help" ]] && usage && exit

if [ -z "$1" ]
then
    /cbio/grlab/share/software/cluster_tools/q-status -alc
else
    /cbio/grlab/share/software/cluster_tools/q-status -lc $1
fi

exit
if [ "$1" != "-nolic" ]
then
	echo "free licenses:"
	qstat -F ml,sigtb,stattb,opttb,imagetb,compiler,simulink,cplex \
		| sort -u \
		| awk '/:.*=/ {print $1}' \
		| sed 's/^g[cfl]://'
fi

echo
#grep currentprice /usr/local/sge/balance
