#!/bin/bash

mem=1gb
user=`whoami`
cpus=1
verbose=0
matlab=""

while [ $# != "0" ];
do
	#	if [ "${1:0:2}" == "-l" ]
	#	then
	#		shift
	#		if [ "${1:0:7}" == "h_vmem=" -o "${1:0:7}" == "s_vmem=" ]
	#	    then	
	#		   mem=${1:7}
	#		fi
		if [ "${1:0:6}" == "--mem=" ]
		then
		   mem=${1:6}
		elif [ "$1" == "-m" ]
		then
		   shift
		   mem=$1
		elif [ "$1" == "-M" ]
		then
		   matlab=":matlab"
		elif [ "$1" == "-n" ]
		then
		   shift
		   cpus=$1
		elif [ "$1" == "-v" ]
		then
		   verbose=1
		elif [ "$1" == "-h" -o "$1" == "--help" ]
		then
		   echo usage "$0 [-m <mem>] [--mem=<mem>] [-M for matlab] [-n <ncpus>] [<additional params in torque format>]"
           exit
        else
            args="$args $1"
		fi		
        shift
done

if [ "$verbose" == "1" ];
then
    echo "qsub -I -l nodes=1:ppn=$cpus$matlab,walltime=72:00:00,mem=$mem,vmem=$mem,pmem=$mem -N QLOGIN -q active $args $@"
fi
qsub -I -l nodes=1:ppn=$cpus$matlab,walltime=72:00:00,mem=$mem,vmem=$mem,pmem=$mem -N QLOGIN -q active $args $@
