#!/bin/bash

mem=1gb
user=`whoami`
cpus=1
verbose=0
time='72:00:00'
x11forward=
queue='active'

while [ $# != "0" ];
do
		if [ "${1:0:6}" == "--mem=" ]
		then
		   mem=${1:6}
		elif [ "$1" == "-t" ]
		then
		   shift
		   time=$1
		elif [ "$1" == "-m" ]
		then
		   shift
		   mem=$1
		elif [ "$1" == "-q" ]
		then
		   shift
		   queue=$1
		elif [ "$1" == "-X" ]
		then
		   shift
		   x11forward="-X"
		elif [ "$1" == "-n" ]
		then
		   shift
		   cpus=$1
		elif [ "$1" == "-v" ]
		then
		   verbose=1
		elif [ "$1" == "-h" -o "$1" == "--help" ]
		then
		   echo usage "$0 [-X] [-t <time>] [-m <mem>] [--mem=<mem>] [-n <ncpus>] [-q queue] [<additional params in torque format>]"
           exit
		fi		
		shift
done

if [ "$verbose" == "1" ];
then
    echo "qsub -I $x11forward -l mem=$mem -l nodes=1:ppn=$cpus,walltime=$time -N QLOGIN -q $queue $@"
fi
qsub -I $x11forward -l mem=$mem -l nodes=1:ppn=$cpus,walltime=$time -N QLOGIN -q $queue $@
