#!/bin/bash

mem=1gb
user=`whoami`
cpus=1
verbose=0
matlab=""
time='72:00:00'
x11forward=""

while [ $# != "0" ];
do
	#	if [ "${1:0:2}" == "-l" ]
	#	then
	#		shift
	#		if [ "${1:0:7}" == "h_vmem=" -o "${1:0:7}" == "s_vmem=" ]
	#	    then	
	#		   mem=${1:7}
	#		fi
		if [ "${1:0:6}" == "--mem=" ]
		then
		   mem=${1:6}
		elif [ "$1" == "-t" ]
		then
		   shift
		   time=$1
		elif [ "$1" == "-m" ]
		then
		   shift
		   mem=$1
		elif [ "$1" == "-M" ]
		then
		   matlab=":matlab"
		elif [ "$1" == "-X" ]
		then
		   shift
		   x11forward="-X"
		elif [ "$1" == "-n" ]
		then
		   shift
		   cpus=$1
		elif [ "$1" == "-v" ]
		then
		   verbose=1
		elif [ "$1" == "-h" -o "$1" == "--help" ]
		then
           echo -e "\nThis script is a wrapper for the submission of an interactive login job.\n" 
		   echo "Usage: $0 [-X] [-t <time> ] [-m <mem>] [--mem=<mem>] [-M for matlab] [-n <ncpus>] [<additional params in torque format>]"
           exit
        else
            args="$args $1"
		fi		
		shift
done

if [ "$verbose" == "1" ];
then
    echo "qsub -I $x11forward -l nodes=1:ppn=$cpus$matlab,walltime=$time,mem=$mem,vmem=$mem,pmem=$mem -N QLOGIN -q active $args $@"
fi
qsub -I $x11forward -l nodes=1:ppn=$cpus$matlab,walltime=$time,mem=$mem,vmem=$mem,pmem=$mem -N QLOGIN -q active $args $@
